# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant multi-machine sample setup

$script = <<SCRIPT
# download required packages
apt-get -y update
apt-get -y install git vim python-scapy
SCRIPT


BOX_IMAGE="hashicorp/precise64"
#BOX_IMAGE="bento/ubuntu-19.04"

Vagrant.configure("2") do |config|

  config.vm.define :m do |m|
    m.vm.box = BOX_IMAGE
    m.vm.network :private_network, ip: "10.0.0.10"
    m.vm.hostname = "m"
  end

  config.vm.define :a do |a|
    a.vm.box = BOX_IMAGE
    a.vm.network :private_network, ip: "10.0.0.11"
    a.vm.hostname = "a"
  end

  config.vm.define :b do |b|
    b.vm.box = BOX_IMAGE
    b.vm.network :private_network, ip: "10.0.0.12"
    b.vm.hostname = "b"

   # b.vm.provider :virtualbox do |vb|
   #   # more RAM
   #   vb.customize ["modifyvm", :id, "--memory", "4096"]
   #   # enable promiscuous mode on the public network
   #   vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
   # end
  end

  config.vm.provision "shell", inline: $script
end
