# -*- mode: ruby -*-
# vi: set ft=ruby :

#BOX_IMAGE = "ubuntu/trusty64"
BOX_IMAGE = "generic/ubuntu1904"
Vagrant.configure(2) do |config|
    config.vm.define "client" do |client|
        client.vm.hostname = "client"
        client.vm.box = BOX_IMAGE
        client.vm.network "private_network", ip: "192.168.60.60"
        client.vm.provision "shell",
          inline: "/bin/sh /vagrant/installDev.sh"
    end
end
